In [699]:
import pandas as pd

In [700]:
df = pd.read_excel(r'C:\Users\Administrateur\Ironhack\LAB\DAFT_212\Module_1\Project_Week_3_Data-Preparation\2 -Entrepreneurial competency in university students.xlsx')
df

,EducationSector,Target IndividualProject,Age,Gender,City,Influenced,Perseverance,DesireToTakeInitiative,Competitiveness,SelfReliance,StrongNeedToAchieve,SelfConfidence,GoodPhysicalHealth,MentalDisorder,KeyTraits,ReasonsForLack,Target-ent_competency
0,Engineering Sciences,No,19.0,Male,Yes,No,2.0,2.0,3.0,3.0,2.0,2.0,3.0,Yes,Passion,NaN,1
1,Engineering Sciences,Yes,22.0,Male,No,Yes,3.0,3.0,3.0,4.0,4.0,3.0,4.0,Yes,Vision,Just not interested! (Want to work in the corp...,0
2,Engineering Sciences,No,18.0,Male,Yes,No,3.0,4.0,3.0,3.0,3.0,4.0,4.0,No,Passion,Not willing to start a venture in India and wa...,0
3,Engineering Sciences,Yes,20.0,Male,Yes,Yes,3.0,3.0,3.0,3.0,4.0,3.0,3.0,No,Rrresilience,Not able to take a Financial Risk,0
4,Engineering Sciences,Yes,19.0,Male,Yes,Yes,2.0,3.0,3.0,3.0,4.0,3.0,2.0,Yes,Vision,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,Engineering Sciences,Yes,19.0,Male,Yes,Yes,NaN,5.0,4.0,3.0,4.0,4.0,5.0,Yes,Positivity,NaN,1
215,Engineering Sciences,Yes,19.0,Male,Yes,No,2.0,2.0,2.0,2.0,2.0,2.0,2.0,No,Work Ethic,Just not interested! (Want to work in the corp...,0
216,Engineering Sciences,Yes,22.0,Female,Yes,Yes,3.0,4.0,4.0,3.0,4.0,4.0,3.0,No,Vision,NaN,1
217,Engineering Sciences,No,19.0,male,Yes,No,1.0,2.0,2.0,3.0,3.0,2.0,2.0,No,Passion,Lack of Knowledge,0
218,Engineering Sciences,Yes,18.0,Male,unknown,Yes,3.0,5.0,3.0,5.0,5.0,5.0,2.0,No,Passion,NaN,1

In [701]:
df1=df.copy()
df1

,EducationSector,Target IndividualProject,Age,Gender,City,Influenced,Perseverance,DesireToTakeInitiative,Competitiveness,SelfReliance,StrongNeedToAchieve,SelfConfidence,GoodPhysicalHealth,MentalDisorder,KeyTraits,ReasonsForLack,Target-ent_competency
0,Engineering Sciences,No,19.0,Male,Yes,No,2.0,2.0,3.0,3.0,2.0,2.0,3.0,Yes,Passion,NaN,1
1,Engineering Sciences,Yes,22.0,Male,No,Yes,3.0,3.0,3.0,4.0,4.0,3.0,4.0,Yes,Vision,Just not interested! (Want to work in the corp...,0
2,Engineering Sciences,No,18.0,Male,Yes,No,3.0,4.0,3.0,3.0,3.0,4.0,4.0,No,Passion,Not willing to start a venture in India and wa...,0
3,Engineering Sciences,Yes,20.0,Male,Yes,Yes,3.0,3.0,3.0,3.0,4.0,3.0,3.0,No,Rrresilience,Not able to take a Financial Risk,0
4,Engineering Sciences,Yes,19.0,Male,Yes,Yes,2.0,3.0,3.0,3.0,4.0,3.0,2.0,Yes,Vision,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,Engineering Sciences,Yes,19.0,Male,Yes,Yes,NaN,5.0,4.0,3.0,4.0,4.0,5.0,Yes,Positivity,NaN,1
215,Engineering Sciences,Yes,19.0,Male,Yes,No,2.0,2.0,2.0,2.0,2.0,2.0,2.0,No,Work Ethic,Just not interested! (Want to work in the corp...,0
216,Engineering Sciences,Yes,22.0,Female,Yes,Yes,3.0,4.0,4.0,3.0,4.0,4.0,3.0,No,Vision,NaN,1
217,Engineering Sciences,No,19.0,male,Yes,No,1.0,2.0,2.0,3.0,3.0,2.0,2.0,No,Passion,Lack of Knowledge,0
218,Engineering Sciences,Yes,18.0,Male,unknown,Yes,3.0,5.0,3.0,5.0,5.0,5.0,2.0,No,Passion,NaN,1

In [702]:
df1.columns

Index(['EducationSector', 'Target IndividualProject ', 'Age', 'Gender', 'City',
       'Influenced', 'Perseverance', 'DesireToTakeInitiative',
       'Competitiveness', 'SelfReliance', 'StrongNeedToAchieve',
       'SelfConfidence', 'GoodPhysicalHealth', 'MentalDisorder', 'KeyTraits',
       'ReasonsForLack', 'Target-ent_competency'],
      dtype='object')

In [703]:
df1.columns = df1.columns.str.replace(' ', '')
df1.columns

Index(['EducationSector', 'TargetIndividualProject', 'Age', 'Gender', 'City',
       'Influenced', 'Perseverance', 'DesireToTakeInitiative',
       'Competitiveness', 'SelfReliance', 'StrongNeedToAchieve',
       'SelfConfidence', 'GoodPhysicalHealth', 'MentalDisorder', 'KeyTraits',
       'ReasonsForLack', 'Target-ent_competency'],
      dtype='object')

In [704]:
sorted(df1['EducationSector'].unique())

['Art, Music or Design',
 'Economic Sciences, Business Studies, Commerce and Law',
 'Engineering Sciences',
 'Humanities and Social Sciences',
 'Language and Cultural Studies',
 'Mathematics or Natural Sciences',
 'Medicine, Health Sciences',
 'Others',
 'Teaching Degree (e.g., B.Ed)']

In [705]:
sorted(df1['TargetIndividualProject'].unique())

['No', 'Yes']

In [706]:
sorted(df1['Age'].unique())

[17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, nan]

In [707]:
sorted(df1['Gender'].unique())

['Female', 'Male', 'male']

In [708]:
df1['Gender'].replace({'male': 'Male'}, inplace=True)
df1

,EducationSector,TargetIndividualProject,Age,Gender,City,Influenced,Perseverance,DesireToTakeInitiative,Competitiveness,SelfReliance,StrongNeedToAchieve,SelfConfidence,GoodPhysicalHealth,MentalDisorder,KeyTraits,ReasonsForLack,Target-ent_competency
0,Engineering Sciences,No,19.0,Male,Yes,No,2.0,2.0,3.0,3.0,2.0,2.0,3.0,Yes,Passion,NaN,1
1,Engineering Sciences,Yes,22.0,Male,No,Yes,3.0,3.0,3.0,4.0,4.0,3.0,4.0,Yes,Vision,Just not interested! (Want to work in the corp...,0
2,Engineering Sciences,No,18.0,Male,Yes,No,3.0,4.0,3.0,3.0,3.0,4.0,4.0,No,Passion,Not willing to start a venture in India and wa...,0
3,Engineering Sciences,Yes,20.0,Male,Yes,Yes,3.0,3.0,3.0,3.0,4.0,3.0,3.0,No,Rrresilience,Not able to take a Financial Risk,0
4,Engineering Sciences,Yes,19.0,Male,Yes,Yes,2.0,3.0,3.0,3.0,4.0,3.0,2.0,Yes,Vision,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,Engineering Sciences,Yes,19.0,Male,Yes,Yes,NaN,5.0,4.0,3.0,4.0,4.0,5.0,Yes,Positivity,NaN,1
215,Engineering Sciences,Yes,19.0,Male,Yes,No,2.0,2.0,2.0,2.0,2.0,2.0,2.0,No,Work Ethic,Just not interested! (Want to work in the corp...,0
216,Engineering Sciences,Yes,22.0,Female,Yes,Yes,3.0,4.0,4.0,3.0,4.0,4.0,3.0,No,Vision,NaN,1
217,Engineering Sciences,No,19.0,Male,Yes,No,1.0,2.0,2.0,3.0,3.0,2.0,2.0,No,Passion,Lack of Knowledge,0
218,Engineering Sciences,Yes,18.0,Male,unknown,Yes,3.0,5.0,3.0,5.0,5.0,5.0,2.0,No,Passion,NaN,1

In [709]:
sorted(df1['City'].unique())

['No', 'Yes', 'no', 'unknown']

In [710]:
df1['City'].replace({'no': 'No'}, inplace=True)

In [711]:
sorted(df1['City'].unique())

['No', 'Yes', 'unknown']

In [712]:
sorted(df1['Influenced'].unique())

['No', 'Yes', 'unknown', 'yes']

In [713]:
df1['Influenced'].replace({'yes': 'Yes'}, inplace=True)

In [714]:
sorted(df1['Influenced'].unique())

['No', 'Yes', 'unknown']

In [715]:
sorted(df1['Perseverance'].unique())

[1.0, 2.0, 3.0, 4.0, 5.0, nan]

In [716]:
sorted(df1['DesireToTakeInitiative'].unique())

[1.0, 2.0, 3.0, 4.0, 5.0, nan]

In [717]:
sorted(df1['Competitiveness'].unique())

[1.0, 2.0, 3.0, 4.0, 5.0, nan]

In [718]:
sorted(df1['SelfReliance'].unique())

[1.0, 2.0, 3.0, 4.0, 5.0, nan]

In [719]:
sorted(df1['StrongNeedToAchieve'].unique())

[1.0, 2.0, 3.0, 4.0, 5.0, nan]

In [720]:
sorted(df1['SelfConfidence'].unique())

[1.0, 2.0, 3.0, 4.0, 5.0, nan]

In [721]:
sorted(df1['GoodPhysicalHealth'].unique())

[1.0, 2.0, 3.0, 4.0, 5.0, nan]

In [722]:
df1['MentalDisorder'].unique()

array(['Yes', 'No', nan], dtype=object)

In [723]:
sorted(df1['KeyTraits'].unique())

['Passion',
 'Positivity',
 'Resilience',
 'Rrresilience',
 'Vision',
 'Work Ethic',
 'passion']

In [724]:
df1['KeyTraits'].replace({'passion': 'Passion','Rrresilience':'Resilience' }, inplace=True)

In [725]:
sorted(df1['KeyTraits'].unique())

['Passion', 'Positivity', 'Resilience', 'Vision', 'Work Ethic']

In [726]:
sorted(df1['Target-ent_competency'].unique())

[0, 1]

In [727]:
df1['ReasonsForLack'].unique()

array([nan,
       'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)',
       'Not willing to start a venture in India and waiting for future relocation',
       'Not able to take a Financial Risk',
       'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else), Academic Pressure, Lack of Knowledge, Not able to take a Financial Risk',
       'Academic Pressure, Lack of Knowledge, Not able to take a Financial Risk',
       'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else), Academic Pressure, Parental Pressure',
       'Academic Pressure, Lack of Knowledge, Mental Block',
       'Lack of Knowledge',
       'Academic Pressure, Unwillingness to take risk, Lack of Knowledge',
       'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else), Lack of Knowledge, Parental Pressure, Mental Block',
       'Unwillingness to take risk, Lack of Knowledge, Not able to take a Financial Risk',
       'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else), Unwillingness to take risk, Lack of Knowledge',
       'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else), Academic Pressure, Unwillingness to take risk, Lack of Knowledge, Parental Pressure, Not able to take a Financial Risk',
       'Academic Pressure, Lack of Knowledge',
       'Unwillingness to take risk',
       'Academic Pressure, Lack of Knowledge, Parental Pressure, Mental Block, Not able to take a Financial Risk',
       'Lack of Knowledge, Not willing to start a venture in India and waiting for future relocation',
       'Academic Pressure',
       'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else), Academic Pressure, Unwillingness to take risk, Lack of Knowledge, Parental Pressure, Mental Block, Not able to take a Financial Risk, Not willing to start a venture in India and waiting for future relocation',
       'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else), Lack of Knowledge',
       'Lack of Knowledge, Not able to take a Financial Risk',
       'Lack of Knowledge, Parental Pressure',
       'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else), Not willing to start a venture in India and waiting for future relocation',
       'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else), Academic Pressure, Not able to take a Financial Risk',
       'Parental Pressure, Not able to take a Financial Risk, Not willing to start a venture in India and waiting for future relocation',
       'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else), Academic Pressure, Lack of Knowledge',
       'Academic Pressure, Not able to take a Financial Risk',
       'Mental Block',
       'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else), Lack of Knowledge, Not able to take a Financial Risk, Not willing to start a venture in India and waiting for future relocation',
       'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else), Lack of Knowledge, Not able to take a Financial Risk',
       'Academic Pressure, Unwillingness to take risk, Lack of Knowledge, Parental Pressure, Mental Block, Not able to take a Financial Risk, Not willing to start a venture in India and waiting for future relocation',
       'Academic Pressure, Lack of Knowledge, Not able to take a Financial Risk, Not willing to start a venture in India and waiting for future relocation',
       'Academic Pressure, Lack of Knowledge, Parental Pressure',
       'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else), Unwillingness to take risk',
       'Academic Pressure, Unwillingness to take risk, Parental Pressure, Not able to take a Financial Risk',
       'Not able to take a Financial Risk, Not willing to start a venture in India and waiting for future relocation',
       'Lack of Knowledge, Parental Pressure, Mental Block, Not able to take a Financial Risk',
       'Academic Pressure, Unwillingness to take risk, Not able to take a Financial Risk',
       'Parental Pressure',
       'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else), Not able to take a Financial Risk',
       'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else), Academic Pressure, Lack of Knowledge, Parental Pressure, Not able to take a Financial Risk',
       'Lack of Knowledge, Mental Block, Not able to take a Financial Risk',
       'Lack of Knowledge, Mental Block',
       'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else), Academic Pressure'],
      dtype=object)

In [728]:
import re
lst_reason=[]
for reason in df1.loc[:,'ReasonsForLack']:
    lst_reason.append(re.split(', (?=[A-Z])', str(reason)))
print(lst_reason)

[['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Not willing to start a venture in India and waiting for future relocation'], ['Not able to take a Financial Risk'], ['nan'], ['nan'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Academic Pressure', 'Lack of Knowledge', 'Not able to take a Financial Risk'], ['Academic Pressure', 'Lack of Knowledge', 'Not able to take a Financial Risk'], ['nan'], ['Not willing to start a venture in India and waiting for future relocation'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['nan'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Academic Pressure', 'Parental Pressure'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['Academic Pressure', 'Lack of Knowledge', 'Mental Block'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Lack of Knowledge'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['nan'], ['nan'], ['Academic Pressure', 'Unwillingness to take risk', 'Lack of Knowledge'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Lack of Knowledge', 'Parental Pressure', 'Mental Block'], ['nan'], ['Unwillingness to take risk', 'Lack of Knowledge', 'Not able to take a Financial Risk'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Unwillingness to take risk', 'Lack of Knowledge'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Academic Pressure', 'Unwillingness to take risk', 'Lack of Knowledge', 'Parental Pressure', 'Not able to take a Financial Risk'], ['Lack of Knowledge'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['nan'], ['Academic Pressure', 'Lack of Knowledge'], ['nan'], ['Unwillingness to take risk'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['nan'], ['Academic Pressure', 'Lack of Knowledge', 'Parental Pressure', 'Mental Block', 'Not able to take a Financial Risk'], ['nan'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Lack of Knowledge', 'Not willing to start a venture in India and waiting for future relocation'], ['Not willing to start a venture in India and waiting for future relocation'], ['nan'], ['Not willing to start a venture in India and waiting for future relocation'], ['nan'], ['Academic Pressure'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Academic Pressure', 'Unwillingness to take risk', 'Lack of Knowledge', 'Parental Pressure', 'Mental Block', 'Not able to take a Financial Risk', 'Not willing to start a venture in India and waiting for future relocation'], ['nan'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['Lack of Knowledge'], ['nan'], ['Unwillingness to take risk'], ['Lack of Knowledge'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['Academic Pressure'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['nan'], ['nan'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Lack of Knowledge'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Lack of Knowledge'], ['nan'], ['Lack of Knowledge', 'Not able to take a Financial Risk'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['Unwillingness to take risk'], ['Lack of Knowledge', 'Parental Pressure'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Lack of Knowledge'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Not willing to start a venture in India and waiting for future relocation'], ['nan'], ['Academic Pressure', 'Unwillingness to take risk', 'Lack of Knowledge'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Academic Pressure', 'Not able to take a Financial Risk'], ['Parental Pressure', 'Not able to take a Financial Risk', 'Not willing to start a venture in India and waiting for future relocation'], ['nan'], ['Not willing to start a venture in India and waiting for future relocation'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Academic Pressure', 'Lack of Knowledge'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Academic Pressure', 'Not able to take a Financial Risk'], ['Not willing to start a venture in India and waiting for future relocation'], ['Mental Block'], ['Lack of Knowledge', 'Not able to take a Financial Risk'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Lack of Knowledge', 'Not able to take a Financial Risk', 'Not willing to start a venture in India and waiting for future relocation'], ['Not willing to start a venture in India and waiting for future relocation'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Lack of Knowledge', 'Not able to take a Financial Risk'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Academic Pressure', 'Not able to take a Financial Risk'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Not able to take a Financial Risk'], ['nan'], ['Not willing to start a venture in India and waiting for future relocation'], ['nan'], ['Academic Pressure', 'Unwillingness to take risk', 'Lack of Knowledge', 'Parental Pressure', 'Mental Block', 'Not able to take a Financial Risk', 'Not willing to start a venture in India and waiting for future relocation'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Lack of Knowledge', 'Not able to take a Financial Risk'], ['nan'], ['Not willing to start a venture in India and waiting for future relocation'], ['Academic Pressure', 'Lack of Knowledge', 'Not able to take a Financial Risk', 'Not willing to start a venture in India and waiting for future relocation'], ['nan'], ['Academic Pressure', 'Lack of Knowledge', 'Parental Pressure'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Lack of Knowledge', 'Not able to take a Financial Risk'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Academic Pressure'], ['Lack of Knowledge', 'Parental Pressure'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Academic Pressure', 'Lack of Knowledge', 'Not able to take a Financial Risk'], ['Academic Pressure'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Academic Pressure'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Unwillingness to take risk'], ['Academic Pressure'], ['Academic Pressure'], ['Academic Pressure', 'Unwillingness to take risk', 'Parental Pressure', 'Not able to take a Financial Risk'], ['Not able to take a Financial Risk', 'Not willing to start a venture in India and waiting for future relocation'], ['Lack of Knowledge', 'Parental Pressure', 'Mental Block', 'Not able to take a Financial Risk'], ['Academic Pressure', 'Unwillingness to take risk', 'Not able to take a Financial Risk'], ['Not willing to start a venture in India and waiting for future relocation'], ['Academic Pressure', 'Lack of Knowledge', 'Not able to take a Financial Risk'], ['nan'], ['Parental Pressure'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Academic Pressure'], ['nan'], ['Lack of Knowledge'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['Not able to take a Financial Risk'], ['nan'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Not able to take a Financial Risk'], ['nan'], ['nan'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Academic Pressure', 'Lack of Knowledge', 'Parental Pressure', 'Not able to take a Financial Risk'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Lack of Knowledge', 'Not able to take a Financial Risk'], ['nan'], ['nan'], ['nan'], ['nan'], ['Lack of Knowledge', 'Not able to take a Financial Risk'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['Academic Pressure'], ['Lack of Knowledge', 'Mental Block', 'Not able to take a Financial Risk'], ['Academic Pressure', 'Unwillingness to take risk', 'Lack of Knowledge'], ['nan'], ['nan'], ['nan'], ['nan'], ['nan'], ['Academic Pressure', 'Unwillingness to take risk', 'Lack of Knowledge'], ['nan'], ['Academic Pressure'], ['Unwillingness to take risk'], ['nan'], ['nan'], ['Academic Pressure'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'], ['nan'], ['nan'], ['Lack of Knowledge', 'Mental Block'], ['nan'], ['nan'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Not able to take a Financial Risk'], ['nan'], ['Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)', 'Academic Pressure'], ['nan'], ['Lack of Knowledge'], ['nan']]

In [729]:
possible_reason=set([item for l in lst_reason for item in l])
possible_reason

{'Academic Pressure',
 'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)',
 'Lack of Knowledge',
 'Mental Block',
 'Not able to take a Financial Risk',
 'Not willing to start a venture in India and waiting for future relocation',
 'Parental Pressure',
 'Unwillingness to take risk',
 'nan'}

In [730]:
new_cols = possible_reason
df1 = df1.assign(**dict.fromkeys(new_cols, 0))
df1

,EducationSector,TargetIndividualProject,Age,Gender,City,Influenced,Perseverance,DesireToTakeInitiative,Competitiveness,SelfReliance,...,Target-ent_competency,Not able to take a Financial Risk,Unwillingness to take risk,Academic Pressure,Mental Block,Lack of Knowledge,nan,Not willing to start a venture in India and waiting for future relocation,"Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)",Parental Pressure
0,Engineering Sciences,No,19.0,Male,Yes,No,2.0,2.0,3.0,3.0,...,1,0,0,0,0,0,0,0,0,0
1,Engineering Sciences,Yes,22.0,Male,No,Yes,3.0,3.0,3.0,4.0,...,0,0,0,0,0,0,0,0,0,0
2,Engineering Sciences,No,18.0,Male,Yes,No,3.0,4.0,3.0,3.0,...,0,0,0,0,0,0,0,0,0,0
3,Engineering Sciences,Yes,20.0,Male,Yes,Yes,3.0,3.0,3.0,3.0,...,0,0,0,0,0,0,0,0,0,0
4,Engineering Sciences,Yes,19.0,Male,Yes,Yes,2.0,3.0,3.0,3.0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,Engineering Sciences,Yes,19.0,Male,Yes,Yes,NaN,5.0,4.0,3.0,...,1,0,0,0,0,0,0,0,0,0
215,Engineering Sciences,Yes,19.0,Male,Yes,No,2.0,2.0,2.0,2.0,...,0,0,0,0,0,0,0,0,0,0
216,Engineering Sciences,Yes,22.0,Female,Yes,Yes,3.0,4.0,4.0,3.0,...,1,0,0,0,0,0,0,0,0,0
217,Engineering Sciences,No,19.0,Male,Yes,No,1.0,2.0,2.0,3.0,...,0,0,0,0,0,0,0,0,0,0
218,Engineering Sciences,Yes,18.0,Male,unknown,Yes,3.0,5.0,3.0,5.0,...,1,0,0,0,0,0,0,0,0,0

In [731]:
df2 = df1.copy()

for i in range(len(lst_reason)):
    for r in lst_reason[i]:
        if r in possible_reason:
            #print(i, r)
            df2.loc[i,r]=1
df2

,EducationSector,TargetIndividualProject,Age,Gender,City,Influenced,Perseverance,DesireToTakeInitiative,Competitiveness,SelfReliance,...,Target-ent_competency,Not able to take a Financial Risk,Unwillingness to take risk,Academic Pressure,Mental Block,Lack of Knowledge,nan,Not willing to start a venture in India and waiting for future relocation,"Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)",Parental Pressure
0,Engineering Sciences,No,19.0,Male,Yes,No,2.0,2.0,3.0,3.0,...,1,0,0,0,0,0,1,0,0,0
1,Engineering Sciences,Yes,22.0,Male,No,Yes,3.0,3.0,3.0,4.0,...,0,0,0,0,0,0,0,0,1,0
2,Engineering Sciences,No,18.0,Male,Yes,No,3.0,4.0,3.0,3.0,...,0,0,0,0,0,0,0,1,0,0
3,Engineering Sciences,Yes,20.0,Male,Yes,Yes,3.0,3.0,3.0,3.0,...,0,1,0,0,0,0,0,0,0,0
4,Engineering Sciences,Yes,19.0,Male,Yes,Yes,2.0,3.0,3.0,3.0,...,1,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,Engineering Sciences,Yes,19.0,Male,Yes,Yes,NaN,5.0,4.0,3.0,...,1,0,0,0,0,0,1,0,0,0
215,Engineering Sciences,Yes,19.0,Male,Yes,No,2.0,2.0,2.0,2.0,...,0,0,0,1,0,0,0,0,1,0
216,Engineering Sciences,Yes,22.0,Female,Yes,Yes,3.0,4.0,4.0,3.0,...,1,0,0,0,0,0,1,0,0,0
217,Engineering Sciences,No,19.0,Male,Yes,No,1.0,2.0,2.0,3.0,...,0,0,0,0,0,1,0,0,0,0
218,Engineering Sciences,Yes,18.0,Male,unknown,Yes,3.0,5.0,3.0,5.0,...,1,0,0,0,0,0,1,0,0,0

In [732]:
df2 = df2.rename(columns={'Academic Pressure':'AcademicPressure',
    'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)': 'NotInterested',
    'Lack of Knowledge': 'LackKnowledge', 
    'Mental Block':'MentalBlock', 
    'Not able to take a Financial Risk': 'NotAbleFinancialRisk',
    'Not willing to start a venture in India and waiting for future relocation': "FutureRelocation", 
    'Parental Pressure': 'ParentalPressure',
    'Unwillingness to take risk': 'RiskAdverse',
    'nan': 'n.p.'})
df2

,EducationSector,TargetIndividualProject,Age,Gender,City,Influenced,Perseverance,DesireToTakeInitiative,Competitiveness,SelfReliance,...,Target-ent_competency,NotAbleFinancialRisk,RiskAdverse,AcademicPressure,MentalBlock,LackKnowledge,n.p.,FutureRelocation,NotInterested,ParentalPressure
0,Engineering Sciences,No,19.0,Male,Yes,No,2.0,2.0,3.0,3.0,...,1,0,0,0,0,0,1,0,0,0
1,Engineering Sciences,Yes,22.0,Male,No,Yes,3.0,3.0,3.0,4.0,...,0,0,0,0,0,0,0,0,1,0
2,Engineering Sciences,No,18.0,Male,Yes,No,3.0,4.0,3.0,3.0,...,0,0,0,0,0,0,0,1,0,0
3,Engineering Sciences,Yes,20.0,Male,Yes,Yes,3.0,3.0,3.0,3.0,...,0,1,0,0,0,0,0,0,0,0
4,Engineering Sciences,Yes,19.0,Male,Yes,Yes,2.0,3.0,3.0,3.0,...,1,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,Engineering Sciences,Yes,19.0,Male,Yes,Yes,NaN,5.0,4.0,3.0,...,1,0,0,0,0,0,1,0,0,0
215,Engineering Sciences,Yes,19.0,Male,Yes,No,2.0,2.0,2.0,2.0,...,0,0,0,1,0,0,0,0,1,0
216,Engineering Sciences,Yes,22.0,Female,Yes,Yes,3.0,4.0,4.0,3.0,...,1,0,0,0,0,0,1,0,0,0
217,Engineering Sciences,No,19.0,Male,Yes,No,1.0,2.0,2.0,3.0,...,0,0,0,0,0,1,0,0,0,0
218,Engineering Sciences,Yes,18.0,Male,unknown,Yes,3.0,5.0,3.0,5.0,...,1,0,0,0,0,0,1,0,0,0

In [733]:
stats = df2.describe().transpose()
stats['IQR'] = stats['75%'] - stats['25%']
stats

,count,mean,std,min,25%,50%,75%,max,IQR
Age,205.0,19.756098,1.324366,17.0,19.0,20.0,20.0,26.0,1.0
Perseverance,202.0,3.346535,1.001845,1.0,3.0,3.0,4.0,5.0,1.0
DesireToTakeInitiative,208.0,3.591346,1.163587,1.0,3.0,4.0,5.0,5.0,2.0
Competitiveness,210.0,3.571429,1.118416,1.0,3.0,4.0,4.0,5.0,1.0
SelfReliance,197.0,3.705584,1.066474,1.0,3.0,4.0,5.0,5.0,2.0
StrongNeedToAchieve,211.0,3.914692,1.033866,1.0,3.0,4.0,5.0,5.0,2.0
SelfConfidence,212.0,3.566038,1.122952,1.0,3.0,4.0,4.0,5.0,1.0
GoodPhysicalHealth,212.0,3.566038,1.105941,1.0,3.0,4.0,4.0,5.0,1.0
Target-ent_competency,219.0,0.415525,0.493941,0.0,0.0,0.0,1.0,1.0,1.0
NotAbleFinancialRisk,219.0,0.150685,0.358561,0.0,0.0,0.0,0.0,1.0,0.0
RiskAdverse,219.0,0.073059,0.260830,0.0,0.0,0.0,0.0,1.0,0.0
AcademicPressure,219.0,0.164384,0.371472,0.0,0.0,0.0,0.0,1.0,0.0
MentalBlock,219.0,0.041096,0.198967,0.0,0.0,0.0,0.0,1.0,0.0
LackKnowledge,219.0,0.200913,0.401601,0.0,0.0,0.0,0.0,1.0,0.0
n.p.,219.0,0.415525,0.493941,0.0,0.0,0.0,1.0,1.0,1.0
FutureRelocation,219.0,0.082192,0.275286,0.0,0.0,0.0,0.0,1.0,0.0
NotInterested,219.0,0.287671,0.453714,0.0,0.0,0.0,1.0,1.0,1.0
ParentalPressure,219.0,0.063927,0.245183,0.0,0.0,0.0,0.0,1.0,0.0

In [734]:
choosen_col=['Age', 'Perseverance', 'DesireToTakeInitiative',
       'Competitiveness', 'SelfReliance', 'StrongNeedToAchieve',
       'SelfConfidence', 'GoodPhysicalHealth']

In [735]:
outliers=df2.loc[:, choosen_col]

In [736]:
outliers

,Age,Perseverance,DesireToTakeInitiative,Competitiveness,SelfReliance,StrongNeedToAchieve,SelfConfidence,GoodPhysicalHealth
0,19.0,2.0,2.0,3.0,3.0,2.0,2.0,3.0
1,22.0,3.0,3.0,3.0,4.0,4.0,3.0,4.0
2,18.0,3.0,4.0,3.0,3.0,3.0,4.0,4.0
3,20.0,3.0,3.0,3.0,3.0,4.0,3.0,3.0
4,19.0,2.0,3.0,3.0,3.0,4.0,3.0,2.0
...,...,...,...,...,...,...,...,...
214,19.0,NaN,5.0,4.0,3.0,4.0,4.0,5.0
215,19.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
216,22.0,3.0,4.0,4.0,3.0,4.0,4.0,3.0
217,19.0,1.0,2.0,2.0,3.0,3.0,2.0,2.0
218,18.0,3.0,5.0,3.0,5.0,5.0,5.0,2.0

In [737]:
for col in choosen_col:
    iqr = stats.at[col,'IQR']
    cutoff = iqr * 3
    lower = stats.at[col,'25%'] - cutoff
    upper = stats.at[col,'75%'] + cutoff
    results = outliers[(outliers[col] < lower) | 
                   (outliers[col] > upper)].copy()
    results['Outlier'] = col
    outliers = outliers.append(results)

In [738]:
outliers

,Age,Perseverance,DesireToTakeInitiative,Competitiveness,SelfReliance,StrongNeedToAchieve,SelfConfidence,GoodPhysicalHealth,Outlier
0,19.0,2.0,2.0,3.0,3.0,2.0,2.0,3.0,NaN
1,22.0,3.0,3.0,3.0,4.0,4.0,3.0,4.0,NaN
2,18.0,3.0,4.0,3.0,3.0,3.0,4.0,4.0,NaN
3,20.0,3.0,3.0,3.0,3.0,4.0,3.0,3.0,NaN
4,19.0,2.0,3.0,3.0,3.0,4.0,3.0,2.0,NaN
...,...,...,...,...,...,...,...,...,...
217,19.0,1.0,2.0,2.0,3.0,3.0,2.0,2.0,NaN
218,18.0,3.0,5.0,3.0,5.0,5.0,5.0,2.0,NaN
42,26.0,2.0,3.0,2.0,3.0,3.0,2.0,3.0,Age
68,24.0,4.0,5.0,5.0,4.0,4.0,4.0,5.0,Age
161,25.0,4.0,4.0,3.0,3.0,3.0,4.0,4.0,Age

In [739]:
filtered_outlier=outliers[outliers['Outlier']=='Age']
filtered_outlier

,Age,Perseverance,DesireToTakeInitiative,Competitiveness,SelfReliance,StrongNeedToAchieve,SelfConfidence,GoodPhysicalHealth,Outlier
42,26.0,2.0,3.0,2.0,3.0,3.0,2.0,3.0,Age
68,24.0,4.0,5.0,5.0,4.0,4.0,4.0,5.0,Age
161,25.0,4.0,4.0,3.0,3.0,3.0,4.0,4.0,Age

In [740]:
df2.to_csv('Clean_data.csv')